Hw8
tiginamaria/Java pull request #11
Opened 2019-04-26 07:04 UTC by tiginamaria

2019-05-13 09:17 UTC, yurii-litvinov requested changes

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/.idea/uiDesigner.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Это лучше не выкладывать

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/LightExecutionException.java
> +public class LightExecutionException extends Exception {
Надо комментарии и для исключения тоже

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/LightFuture.java
> +    <R> LightFuture<R> thenApply(Function<T, R> function);
Можно более мягкие ограничения на тип функции

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +        return  Thread.activeCount();
Я бы не сказал, что этот метод имеет какое-то отношение к ThreadPool, так что его тут не стоит реализовывать

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +                synchronized(taskQueue) {
Пробела не хватает

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +        Task<T> task = new Task<>(supplier);
var?

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +    }
Если потом кто-то сделает execute, ему вернут LightFuture, который никогда не закончит вычисление просто потому, что все потоки остановлены и делать его некому. Вызов get у такого LightFuture приведёт к дедлоку

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +    }
Кроме того, хочется, чтобы shutdown возвращал управление только когда все потоки уже полностью остановлены.

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +            while(!isReady.get()) {
Тоже пробела не хватает

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +                    taskQueue.notifyAll();
Как-то это делается в обход ThreadPoolImpl-а, это может привести к проблемам с shutdown и вообще стрёмно :)

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/test/java/ru/hse/hw/ThreadPoolImplTest.java
> +            array.add(new Random().nextInt());
Этак у Вас все значения в массиве могут оказаться одинаковыми. На некоторых платформах (где нет /dev/random) конструктор может использовать в качестве сида значение системного таймера в миллисекундах, а этот цикл легко уместится в одну миллисекунду даже несмотря на то, что это Java.

Кроме того, сборщик мусора тысяче Random-ов не обрадуется. Стандартный паттерн --- использовать один Random на весь класс или даже на всё приложение.

2019-05-13 09:17 UTC, yurii-litvinov commented on ThreadPool/src/test/java/ru/hse/hw/ThreadPoolImplTest.java
> +        ArrayList<Integer> array = new ArrayList<>(size);
var?

2019-05-18 08:54 UTC, tiginamaria commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +        return  Thread.activeCount();
Он нужен для тестов.

2019-06-09 11:51 UTC, yurii-litvinov requested changes

2019-06-09 11:51 UTC, yurii-litvinov commented on Phonebook/pom.xml
>      <modelVersion>4.0.0</modelVersion>
Что-то лишние файлы в диффе

2019-06-09 11:51 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +        Task<T> task = new Task<>(supplier);
var :)

2019-06-09 11:51 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +    }
Тут лучше сначала всем разослать interrupt(), затем всем сделать join(). Иначе какая-нить вычислительно сложная задача может сильно замедлить процесс.

2019-06-09 11:51 UTC, yurii-litvinov commented on ThreadPool/src/main/java/ru/hse/hw/ThreadPoolImpl.java
> +            isReady.set(true);
Тут set делается не под замком, поэтому могут быть гонки с thenApply --- там мы рискуем добавить задачи в очередь как раз в тот момент, когда тут сделается isReady.set(true) и задачи никто не исполнит (synchronized (thenApplyTasks) в executeThenApplyLightFuture тоже не очень спасёт, решение ведь принимается на основе thenApply).

2019-07-10 10:05 UTC, merged